<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ShortenerController extends AbstractController
{
    #[Route('/{url?}', name: 'shortener')]
    public function index(?String $created, ?String $endpoint,?bool $autogenerated, ?String $url, Request $req): Response
    {   

        if($_SERVER["REQUEST_METHOD"] === "GET" && !is_null($url) ){
            return $this->forward('App\Controller\UrlAddressController::redirection', ['finalRedirection' => $url]);
        }

        if(!is_null($endpoint)){
            return $this->render('shortener/index.html.twig', [
                'created' => $created, 'endpoint' => $endpoint, 'autogenerated' => $autogenerated
            ]);
        }

        return $this->render('shortener/index.html.twig');
    }

    #[Route('/create/autogenerated', name: 'autogenerated')]
    public function autogenerated(Request $req): Response
    {   
        define('URL_PATTERN', "/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)(:[0-9]{0,5})?(#[\w]*)?((?:\/[\+~%\/.\w\-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)/i");

        $urlOriginal = $req->request->get('url');

        $validUrl = preg_match(URL_PATTERN, $urlOriginal);

        if($validUrl !== 1){
            return $this->render('shortener/index.html.twig', ['invalidAutogenerated'=> 'La URL introducida no es valida.']);
        }

        $autogeneratedURL = bin2hex(random_bytes(6));


        return $this->forward('App\Controller\UrlAddressController::createUrlAddress', ['urlEndpoint' => $autogeneratedURL, 'realUrl' => $urlOriginal, 'autogenerated' => true]);
    }

    #[Route('/create/custom', name: 'custom')]
    public function custom(Request $req): Response
    {   
        define('URL_PATTERN', "/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)(:[0-9]{0,5})?(#[\w]*)?((?:\/[\+~%\/.\w\-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)/i");

        define('ENDPOINT_PATTERN', "/^[A-Za-z0-9]{7,15}$/i");

        $urlOriginal = $req->request->get('urlCustom');

        $nuevaUrl = $req->request->get('endpoint');

        $validUrl = preg_match(URL_PATTERN, $urlOriginal);


        $validEndpoint = preg_match(ENDPOINT_PATTERN, $nuevaUrl);

        if($validUrl !== 1){
            return $this->render('shortener/index.html.twig', ['invalidCustom'=> 'La URL introducida no es valida.']);
        }

        if($validEndpoint !== 1){
            return $this->render('shortener/index.html.twig', ['invalidEndPoint'=> 'La URL introducida no es valida. Solo caracteres alfanuméricos.']);
        }

        return $this->forward('App\Controller\UrlAddressController::createUrlAddress', ['urlEndpoint' => $nuevaUrl, 'realUrl' => $urlOriginal, 'autogenerated' => 0]);
    }
}
